# Generated by Django 4.0.2 on 2022-03-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalicao',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
