# Generated by Django 4.0.2 on 2022-03-03 16:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pontoturistico_enderecos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avaliacoes', '0002_alter_avalicao_nota'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avalicao',
            new_name='Avaliacao',
        ),
    ]
